Acclimatising the command bowtie2_extract_reads_mapped_to_specific_contigs.pl failed with error
Traceback (most recent call last):
  File "/home/ubuntu/BiocondaCli/bioconda_cli/main.py", line 313, in commands_from_package
    [exe.name], run_kwargs={"cwd": dir}
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 179, in explore_command
    command = best_cmd(cmd, flags, run_kwargs=run_kwargs)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 101, in best_cmd
    final = execute_cmd(help_cmd, **run_kwargs)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/execution.py", line 43, in execute_cmd
    with subprocess.Popen(help_cmd, **popen_kwargs) as process:
  File "/mnt/miniconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/mnt/miniconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bowtie2_extract_reads_mapped_to_specific_contigs.pl': 'bowtie2_extract_reads_mapped_to_specific_contigs.pl'
