!Command
command:
- galaxy-manage-db
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/galaxy-manage-db\"\
  , line 10, in <module>\n    sys.exit(manage_db())\n  File \"/usr/local/lib/python3.6/site-packages/galaxy/model/orm/scripts.py\"\
  , line 145, in manage_db\n    config = get_config(sys.argv, use_argparse=False,\
  \ cwd=os.getcwd())\n  File \"/usr/local/lib/python3.6/site-packages/galaxy/model/orm/scripts.py\"\
  , line 138, in get_config\n    db_url = \"sqlite:///%s?isolation_level=IMMEDIATE\"\
  \ % os.path.join(get_data_dir(properties), default_sqlite_file)\n  File \"/usr/local/lib/python3.6/site-packages/galaxy/util/properties.py\"\
  , line 205, in get_data_dir\n    config_dir = properties.get('config_dir', os.path.dirname(properties['__file__']))\n\
  \  File \"/usr/local/lib/python3.6/posixpath.py\", line 156, in dirname\n    p =\
  \ os.fspath(p)\nTypeError: expected str, bytes or os.PathLike object, not NoneType\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/galaxy-data:20.9.1--py_2
