Acclimatising the command vargeno failed with error
Traceback (most recent call last):
  File "/home/ubuntu/BiocondaCli/bioconda_cli/main.py", line 313, in commands_from_package
    [exe.name], run_kwargs={"cwd": dir}
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 179, in explore_command
    command = best_cmd(cmd, flags, run_kwargs=run_kwargs)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 102, in best_cmd
    result = parse_help(cmd, final)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 58, in parse_help
    usage_command = parse_usage(cmd, text)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/usage_parser/__init__.py", line 20, in parse_usage
    toks = usage.setDebug(debug).searchString(text)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 2103, in searchString
    return ParseResults([t for t, s, e in self.scanString(instring, maxMatches)])
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 2103, in <listcomp>
    return ParseResults([t for t, s, e in self.scanString(instring, maxMatches)])
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 2007, in scanString
    nextLoc, tokens = parseFn(instring, preloc, callPreParse=False)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4069, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4707, in parseImpl
    loc, tmptokens = self_expr_parse(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4164, in parseImpl
    loc2, toks = expr1._parse(instring, loc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4069, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4697, in parseImpl
    loc, tokens = self_expr_parse(instring, loc, doActions, callPreParse=False)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4164, in parseImpl
    loc2, toks = expr1._parse(instring, loc, doActions)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1716, in _parseNoCache
    tokens = fn(instring, tokensStart, retTokens)
  File "/mnt/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1316, in wrapper
    ret = func(*args[limit[0]:])
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/usage_parser/elements.py", line 132, in visit_list_element
    el.repeatable = True
AttributeError: 'str' object has no attribute 'repeatable'
