Traceback (most recent call last):
  File "/home/ubuntu/BiocondaCli/bioconda_cli/main.py", line 389, in generate_wrapper
    exhaust(WdlGenerator().generate_tree(cmd, output_path))
  File "/home/ubuntu/BiocondaCli/bioconda_cli/main.py", line 357, in exhaust
    for _ in gen:
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/converter/__init__.py", line 77, in generate_tree
    self.save_to_file(cmd, path)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/converter/__init__.py", line 68, in save_to_file
    path.write_text(self.save_to_string(cmd))
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/converter/wdl.py", line 175, in save_to_string
    parameter_meta=self.make_parameter_meta(names),
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/converter/wdl.py", line 158, in make_parameter_meta
    return ParameterMeta(**params)
TypeError: __init__() got multiple values for argument 'self'
