!Command
command:
- fc_run
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "pypeflow 2.3.0\nTraceback (most recent call last):\n  File \"/usr/local/bin/fc_run\"\
  , line 11, in <module>\n    load_entry_point('falcon-kit==0.4.0', 'console_scripts',\
  \ 'fc_run')()\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 489, in load_entry_point\n    return get_distribution(dist).load_entry_point(group,\
  \ name)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 2852, in load_entry_point\n    return ep.load()\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 2443, in load\n    return self.resolve()\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\"\
  , line 2449, in resolve\n    module = __import__(self.module_name, fromlist=['__name__'],\
  \ level=0)\n  File \"/usr/local/lib/python2.7/site-packages/falcon_kit/mains/run.py\"\
  , line 3, in <module>\n    from pypeflow.data import PypeLocalFile, makePypeLocalFile,\
  \ fn\nImportError: No module named data\n"
generated_using:
- --help
