!Command
command:
- cyvcf2
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/cyvcf2\",\
  \ line 33, in <module>\n    sys.exit(load_entry_point('cyvcf2==0.30.4', 'console_scripts',\
  \ 'cyvcf2')())\n  File \"/usr/local/lib/python3.6/site-packages/click/core.py\"\
  , line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/click/core.py\"\
  , line 760, in main\n    _verify_python3_env()\n  File \"/usr/local/lib/python3.6/site-packages/click/_unicodefun.py\"\
  , line 130, in _verify_python3_env\n    \" mitigation steps.{}\".format(extra)\n\
  RuntimeError: Click will abort further execution because Python 3 was configured\
  \ to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/\
  \ for mitigation steps.\n\nAdditional information: on this system no suitable UTF-8\
  \ locales were discovered. This most likely requires resolving by reconfiguring\
  \ the locale system.\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/cyvcf2:0.30.4--py36he01d083_0
