!Command
command:
- shrec.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/shrec.py\"\
  , line 17, in <module>\n    from matplotlib import pyplot as plt\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py\"\
  , line 115, in <module>\n    _backend_mod, new_figure_manager, draw_if_interactive,\
  \ _show = pylab_setup()\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/__init__.py\"\
  , line 63, in pylab_setup\n    [backend_name], 0)\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py\"\
  , line 4, in <module>\n    from . import tkagg  # Paint image to Tk photo blitter\
  \ extension.\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py\"\
  , line 5, in <module>\n    from six.moves import tkinter as Tk\n  File \"/usr/local/lib/python2.7/site-packages/six.py\"\
  , line 203, in load_module\n    mod = mod._resolve()\n  File \"/usr/local/lib/python2.7/site-packages/six.py\"\
  , line 115, in _resolve\n    return _import_module(self.mod)\n  File \"/usr/local/lib/python2.7/site-packages/six.py\"\
  , line 82, in _import_module\n    __import__(name)\n  File \"/usr/local/lib/python2.7/lib-tk/Tkinter.py\"\
  , line 39, in <module>\n    import _tkinter # If this fails your Python may not\
  \ be configured for Tk\nImportError: libX11.so.6: cannot open shared object file:\
  \ No such file or directory\n"
generated_using:
- --help
